Updated Lit Review and lit review for Non-US countires
kbuzard-SU/gradualism pull request #104
Opened 2021-07-02 04:21 UTC by Kirs10-Riley

These are the revised lit review and a separate rmd file with articles pertaining to articles with data that are outside of the US. I marked where the newly added articles begin. In the non-US lit review I moved Canada over even though they did talk about the US because they only mentioned US data that was relevant to Canada and it was such a small portion of the article. If you want me to put it back to the US lit review file I will.

2021-07-03 15:28 UTC, kbuzard requested changes
The non-U.S. lit review looks great.

For the U.S. one, I'm beginning to see that I wasn't clear about my feedback on the first set of papers. I apologize. For every paper, I need the details about the data that you added for the Balassa paper (number 2). Please address the comments below and then apply the principles from here and the last set of comments throughout all the rest of these papers you've already found, then submit an updated PR

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +-Notes: This article looks at tariffs among the industrial counties (US, Belgium, France, Germany, Italy, and Netherlands). They use export data from 1958 of 91 manufacturing industries. The years fo
@Kirs10-Riley, this is exactly the detailed info that I was looking for! Thanks!

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +-   Notes: The author said on page 630 that, "the estimation of sector growth functions in the present paper is therefore based on data for a number of countries, mainly for years between 1950-1956."
Can you find out who many "sectors"? How much the data are aggregated is a key thing I need to know. Something as simple as the 91 manufacturing industries in the Balassa paper is plenty of information.

Also, you could take off everything in the first paragraph after [2], and please proof-read the excerpts you copy over and fix up the typos that are induced by pasting from a PDF (sometimes spaces are missing between words, there are dashes that aren't necessary, and sometimes you'll find that anything with a "ff" gets turned to something weird or entirely left out--I've never figured out why that happens). Please do this throughout, and going forward.

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +- Notes: The author used estimates of the effects of the concessions on the US imports, with separate figures for imports from developed countries and from the less developed countries mentioned in t
If there is no industry or good type disaggregation (e.g., if it's only total imports) please say that explicitly

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +-   Notes: paper looks at data from the GATT negotiations in 1955 and 1956 to examine the effect of the US tariff reduction program on the prices and volume of imports subject to tariff concessions.
how disaggregated is their data?

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +-   main point of intro "The intent of this paper is to estimate a model of international trade and to use that model to construct tariff averages. In section 1 we shall describe a fairly complete tr
how many commodities?

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +*NEW ENTRIES*
Thanks! This is helpful!

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +-   "intro: At the Kennedy Round the major industrial countries agreed to tariff reductions of about one-third of the initial level on about one-third of their total or two-thirds of their dutiable i
How does this relate to the paper above by Finger in the same journal? And to what level is the data disaggregated?

2021-07-03 15:28 UTC, kbuzard commented on lit review.Rmd
> +9. Kowalczyk, Carsten and Davis, Donald. "8. Tariff Phase-Outs: Theory and Evidence from GATT and NAFTA". The Regionalization of the World Economy, edited by Jeffrey A. Frankel, Chicago: University o
This is interesting, but seems like it's not actually looking at tariff, import or export data. If that's true, then please make yet another .rmd called "lit-review-other.rmd" and put this in there.

2021-07-03 15:28 UTC, kbuzard commented on Lit Review (non-US).Rmd
> +-   Notes: Includes data on the US demand for Canadian Exports. But beyond that this only talks about Canada so I moved it to the non-US list.
I agree with this decision. Thanks!

2021-07-07 02:46 UTC, Kirs10-Riley commented on Lit Review (non-US).Rmd
> +-   Notes: Includes data on the US demand for Canadian Exports. But beyond that this only talks about Canada so I moved it to the non-US list.
@kbuzard I uploaded the most updated version of the US Lit review with all the changes mentioned above, please let me know if you can see it.

2021-07-07 14:17 UTC, kbuzard commented on Lit Review (non-US).Rmd
> +-   Notes: Includes data on the US demand for Canadian Exports. But beyond that this only talks about Canada so I moved it to the non-US list.
> @kbuzard I uploaded the most updated version of the US Lit review with all the changes mentioned above, please let me know if you can see it.

Yes, I can see them! I should be able to get you feedback on this today.

2021-07-07 20:41 UTC, kbuzard approved these changes
@Kirs10-Riley , the earlier entries that you revised look good. The non-U.S. file looks good. I need more details on many of the new additions--notes are throughout this review. I'm going to merge these changes; please respond to the feedback in a new pull request, only adding any new papers that come from the couple of reviews where I added a note asking you to drill down into the papers that are surveyed.

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +9. Kowalczyk, Carsten and Davis, Donald. "8. Tariff Phase-Outs: Theory and Evidence from GATT and NAFTA". The Regionalization of the World Economy, edited by Jeffrey A. Frankel, Chicago: University o
I don't see anything new here to answer the question from above

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   Intro: "Tpursuit of the sources of comparative advantage for a country is closely related to the analysis of the welfare and income distri- bution effects of trade policy. In other words, as trad
It seems to me that the value of this paper is in collecting other papers together that might be interesting for us. Please look into the papers that Hartigan reviews here.

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   Publisher Summary: "This chapter focuses on the international trade theory. It discusses the Ricardian and the Ricardo--Viner models. These models point to technological differences as the source
This will only be useful to us if some of the empirical studies it reviews are ones that should be added to the list. Please follow up on the empirical studies (my guess is that they aren't going to be very disaggregated) and then remove this from the list.

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   ABSTRACT:"Despite the gravity equations' empirical successes in "explaining" trade flows, the model's predictive potential has been inhibited by an absence of strong theoretical foundations. A ge
I need details on the data from the 'empirical evidence' section to know whether this should stay on the list. Please add.

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   Intro: "GNERALIZATIONS about economic development have two main sources: historical studies of advanced countries and com- parisons among countries at different income levels. The third possibili
I can't tell from what you've written here whether this even involved trade data. I need these details for *every* paper.

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   Publisher Summary: "The major obstacle to the testing of trade theories has been the difficulty of constructing tests that is theoretically sound. The intuitive content of most trade theories is
Like (13) above, this will only be useful to us if some of the empirical studies it reviews are ones that should be added to the list. Please follow up on the empirical studies (my guess is that they aren't going to be very disaggregated) and then remove this from the list.

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +18. Helpman, Ethan "Imperfect Competition and International Trade: Evidence from fourteen Industrial Countries". *Journal of the Japanese and International Economies*, Volume I, 62-81. 1987. Departme
This is Elhanan Helpman, not Ethan (he's SUPER well known).

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   Abstract: "Three hypotheses that emerge from a theoretical model are discussed. Two of them concern the behavior of the share of intraindustry trade while the third concerns the volume of trade.
The bib information doesn't need to be repeated.

There are no details about the data here for me to be able to judge this.

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +Comment: This is a book, I would skip to the chapter called "some imperical evidence"
I agree that this sounds like the reasonable thing to do. The question is how to access that chapter.
- Is this a book you can access online? If not, check to see if we have it in the library here, or

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   Comment: Another Book, I only looked at chapter 1
It's possible that this is one that we want to keep on our list, but we need more details on the data.
- Also, I can't tell if the title is for the book or for the chapter, so I'm a little lost.
  - When you come across books like this, if you can provide a link to a table of contents, that would be really helpful

2021-07-07 20:41 UTC, kbuzard commented on lit review.Rmd
> +-   intro: "This study is concerned with an examination and evaluation of the importance and impact of the WebbPomerene Export Trade Act of 1918. The Act is representative of a unique position in the
I can't tell anything from this blurb about the data that is used (what years, what series, what countries, level of disaggregation).

2021-07-07 20:42 UTC, merged