Updated Lit-Review (new document)
kbuzard-SU/gradualism pull request #109
Opened 2021-08-14 02:40 UTC by Kirs10-Riley

I created a new document because the old started to get unorganized.  I have added more papers and removed a few. I tried to keep track of all the papers I removed and created a section below of the ones I took out and a small reason explaining why. I added all the notes that was left in the last pull-request as well.

2021-08-16 16:28 UTC, kbuzard requested changes
@Kirs10-Riley Thanks for this update! I've gotten down to #22 and I'll have to finish the rest later. But I wanted to get these comments to you now.

2021-08-16 16:28 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +-   Abstract: "Four political models (the international system, rational domestic economic policy, intra-govemmental politics, and interest group influence) may explain the cross-national structure o
Can you give me a better idea of how detailed the data is? If it's all at the country level (no industrial/sectoral detail), please say that.

Also, we don't need the doi at the top repeated at the bottom.

2021-08-16 16:28 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +
Is this all about NAFTA? I can't tell what years the data covers. If the data doesn't start before 1988, we don't need this one.

2021-08-16 16:28 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +*LOOK INTO THE PAPERS IN 10*
What is the status of this note?

2021-08-16 16:28 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +\- Abstract: "Both DC (developed country) tariffs and LDC (developing country) export taxes are "escalated" to protect local processors of primary commodities. The paper develops an analytical model
How does this involve U.S. data? What years does it cover?

2021-08-16 16:28 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +-   Notes: US trade data on page 484, 489, and 497. He uses import data, export data, import/ export, net exports, production, and consumption for different factor content of US trade.
What years? If there's no sectoral/industrial detail, please say that explicitly.

2021-08-16 16:28 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +-   Comment: This is a book, I would skip to the chapter called "some imperial evidence" can be found in the SU Library ISBN: 0262111594 9780262111591 or Bird 4th floor.
here you have "imperial" but I think you mean "empirical." I've seen this a couple other places. If I'm right that this should be "empirical," please fix it here and anywhere else it shows up in the document

2021-08-16 18:18 UTC, kbuzard requested changes
Okay--I've finished this up. There are a few more questions, but overall this is in good shape. I think it's totally do-able to clean this up by the end of the week. What do you think @Kirs10-Riley ?

2021-08-16 18:18 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +-   Intro: "This paper analyzes the economic efficiency effects of tariff concessions made in the Kennedy Round trade negotiations. The static welfare methodology used differs from previous analyses
Please add the years and whether or not there is sectoral/industrial detail.

2021-08-16 18:18 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +-   Notes: The product and industrial classification unites in the general equilibrium trade models are listed in table 1, page 843. The data used is from GATT (1974), Yeats (1976;1977)
Is the data for the year 1974, or is this a reference to a GATT publication? Bottom line: I want to know what years of data they have.

Can you also add a few words about how detailed the product/industrial classification is? We want to be able to know at a glance what's going on without having to go get access to the paper.

2021-08-16 18:18 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +    1.  Reason: Paper focuses on a generalized gravity equation and the "emperical evidence" he used does not specify an exact country.
please turn these indented "1." 's into bullets or similar--the numbering is confusing.

This explanations for why this was removed for the Bergstrand paper and 4 and 5 (below) are perfect.

2021-08-16 18:18 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +1.  Edward E. Leamer, James Levinsohn, Chapter 26 "International trade theory: The evidence, Handbook of International Economics", Elsevier, Volume 3,1995, Pages 1339-1394, ISSN 1573-4404, ISBN 97804
Explanation for why removed is missing.

2021-08-16 18:18 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +    1.  reason: trade is not the main focus of the paper.
The explanation doesn't make clear whether there is NO trade data. If there is trade data in there, we might want it in the lit review.

2021-08-16 18:18 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +    1.  does not fit very well.
This isn't a convincing explanation for excluding this paper. We need to know whether it uses data, and if so, whether that data is of interest to us (years of data, etc).

2021-08-16 19:03 UTC, Kirs10-Riley commented
> Okay--I've finished this up. There are a few more questions, but overall this is in good shape. I think it's totally do-able to clean this up by the end of the week. What do you think @Kirs10-Riley ?

I'll have it done by this week.

2021-08-16 19:08 UTC, Kirs10-Riley commented on LIT-REVIEW.Rmd
> +*LOOK INTO THE PAPERS IN 10*
I forgot to deleted this comment. I looked at them. Most of the papers below are from this document.

2021-08-16 22:47 UTC, kbuzard commented on LIT-REVIEW.Rmd
> +*LOOK INTO THE PAPERS IN 10*
Great! When you've deleted that from the updated version, go ahead and resolve this conversation.

2021-08-20 05:51 UTC, Kirs10-Riley commented
@kbuzard Here is the completed Literature Review.

2021-08-20 17:18 UTC, merged

2021-08-20 17:18 UTC, kbuzard commented
@Kirs10-Riley It looks great! Thank you. I'm going to merge it into the repo and you can consider this task finished. Great work!