Create data (draft).rmd
kbuzard-SU/gradualism pull request #84
Opened 2021-04-29 16:03 UTC by Zeyuan-Xiong

2021-04-30 13:30 UTC, kbuzard requested changes
This is in VERY good shape. I had a few questions I've noted here--will you address them and then update the pull request?

2021-04-30 13:30 UTC, kbuzard commented on data-paper/data (draft).rmd
> +The tax schedules of United States went through two systematically tariff schedules changes from the first round of GATT negotiation, Geneva 1947, to the last round of negotiation, Uruguay 1992. The
Is there a reason to use "tax schedules"? e.g. is the word "tax" used in official government documents? If not, it will be less confusing for the reader to always use the word "tariff" as "tax" is usually associated with a domestic tax (sales tax, income tax, etc).

2021-04-30 13:30 UTC, kbuzard commented on data-paper/data (draft).rmd
> +Some other issues arose during the digitization process, including dealing with tax intervals, more specified product description and staging process for certain products (that products facing tax re
What does "more details can be found in description in our data set" mean? Do you mean the information that is going into the data appendix?

Let's include here how many different units there are in our raw data and how  many we consolidate to. Also a reference to where someone could see the list of units.

2021-05-01 13:12 UTC, Zeyuan-Xiong commented on data-paper/data (draft).rmd
> +The tax schedules of United States went through two systematically tariff schedules changes from the first round of GATT negotiation, Geneva 1947, to the last round of negotiation, Uruguay 1992. The
Actually I think the tariff schedule is a more common way used in the general schedule, I will correct this one and also uniform the way of saying this. Thanks for the reminder!

2021-05-01 13:16 UTC, Zeyuan-Xiong commented on data-paper/data (draft).rmd
> +Some other issues arose during the digitization process, including dealing with tax intervals, more specified product description and staging process for certain products (that products facing tax re
There are many (over 20) types of units in the units keys system and I feel it will be too trivial to include them all here. The detailed mapping and transformation of all the units (namely the units normalization process) is already documented in the unit keys sheet in the excel data we have on OneDrive. But if you think it is better to include this information, I can attach them later in the data.appendix section.

2021-05-01 19:34 UTC, kbuzard commented on data-paper/data (draft).rmd
> +Some other issues arose during the digitization process, including dealing with tax intervals, more specified product description and staging process for certain products (that products facing tax re
Oh, sorry I wasn't clearer. I just meant a two summary stats: how many total units did we find in the raw data, and how many were we able to get down to after standardization?

2021-05-03 13:43 UTC, Zeyuan-Xiong commented on data-paper/data (draft).rmd
> +Some other issues arose during the digitization process, including dealing with tax intervals, more specified product description and staging process for certain products (that products facing tax re
I see, I think I can add this part after Tokyo round is mostly finished, it seems there are one or two units in TSUSA, I want to include them as well.

2021-05-11 17:58 UTC, Zeyuan-Xiong commented on data-paper/data (draft).rmd
> +Some other issues arose during the digitization process, including dealing with tax intervals, more specified product description and staging process for certain products (that products facing tax re
Oh, sorry, I wasn't clearer for this question: ""more details can be found in description in our data set" means."

What I mean is that the detailed steps are listed in the sheet "Units Keys" in the OneDrive excel file (I suppose we will have that as part of the data package, or we can separate it from the main data to create a individual document for it), it includes more details: which units are normalized, and for what reason they are normlized and how many units are left after the normalization.

Thanks for the reminder, I will correct them now.

2021-05-12 16:19 UTC, merged